- name: Set executable permissions on target.sh
  command: chmod +x ./target.sh
  args:
    chdir: "{{ app_dir }}"

- name: Run target.sh script to deploy Jenkins
  command: "./target.sh"
  args:
    chdir: "{{ app_dir }}"

- name: Verify Jenkins is accessible
  command: "kubectl get ingress -n jenkins"
  register: ingress_status
  failed_when: "'jenkins' not in ingress_status.stdout"

- name: Get Route53 hosted zone ID
  command: aws route53 list-hosted-zones-by-name --dns-name "{{ dns_domain }}." --query "HostedZones[0].Id" --output text
  register: hosted_zone_id
  failed_when: hosted_zone_id.stdout == ""

- name: Get Route53 record for Jenkins
  command: aws route53 list-resource-record-sets --hosted-zone-id {{ hosted_zone_id.stdout }} --query "ResourceRecordSets[?Name=='{{ jenkins_dns }}.']" --output json
  register: dns_record

- name: Fail if Jenkins DNS record is not found
  fail:
    msg: "Jenkins DNS record {{ jenkins_dns }} not found in Route53!"
  when: dns_record.stdout == "[]"
