apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.jenkins.io"
    targetRevision: "5.8.24"
    chart: "jenkins"
    helm:
      values: |
        controller:
          javaOpts: "-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"
          serviceType: ClusterIP
          jenkinsUrl: https://jenkins.k8s.it.com
          installPlugins:
            - github:1.32.0
            - kubernetes:1.32.0
            - workflow-aggregator:2.6
            - git:4.11.0
            - configuration-as-code:1.55
            - credentials-binding:1.27
            - matrix-auth:2.6.6
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: jenkins-alb
            kubernetes.io/ingress.class: alb

          # ✅ Adăugare credentiale prin JCasC
          existingSecret: secret-credentials
          additionalExistingSecrets:
            - name: secret-credentials
              keyName: github-username
            - name: secret-credentials
              keyName: github-password

          JCasC:
            configScripts:
              credentials-config: |
                credentials:
                  system:
                    domainCredentials:
                    - credentials:
                      - usernamePassword:
                          description: "GitHub access username password"
                          id: "github-token"
                          password: ${secret-credentials-github-password}
                          scope: GLOBAL
                          username: ${secret-credentials-github-username}

        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: jenkins-alb
            kubernetes.io/ingress.class: alb
          hostName: jenkins.k8s.it.com
          paths:
            - path: /
              pathType: ImplementationSpecific
          tls: []
        persistence:
          enabled: true
          storageClass: "gp2"
          size: "8Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
