apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: copy-html
          image: alpine:latest
          command: ["/bin/sh", "-c", "cp -r /src/. /html/"]
          volumeMounts:
            - name: html-volume
              mountPath: /html
            - name: source-volume
              mountPath: /src
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: tmp-volume
              mountPath: /tmp
          command: ["nginx", "-g", "daemon off;"]

        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.10.0
          args:
            - "-nginx.scrape-uri=http://127.0.0.1:80/metrics"
          ports:
            - containerPort: 9113

      volumes:
        - name: html-volume
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: config-volume
          configMap:
            name: nginx-config
        - name: tmp-volume
          emptyDir: {}
        - name: source-volume
          configMap:
            name: nginx-html-configmap