############################################
# Wait for LoadBalancer IPs to be assigned
############################################

- name: Wait for LoadBalancer IPs to be assigned
  shell: |
    kubectl get svc -n {{ item.namespace }} {{ item.name }} -o jsonpath="{.status.loadBalancer.ingress[0].ip}"
  register: svc_ip
  until: svc_ip.stdout != ""
  retries: 20
  delay: 15
  with_items:
    - { name: argo-argocd-server, namespace: argocd }
    - { name: jenkins, namespace: jenkins }
    - { name: grafana, namespace: monitoring }
    - { name: nginx-service, namespace: default }

############################################
# Create Route53 records
############################################

- name: Create Route53 records
  route53:
    zone: "{{ hosted_zone_id }}"
    record: "{{ item.name }}"
    type: A
    ttl: 300
    value: "{{ item.ip }}"
    state: present
  loop: "{{ dns_records }}"
  vars:
    dns_records:
      - { name: "argo-azure.k8s.it.com", ip: "{{ svc_ip.results[0].stdout }}" }
      - { name: "jenkins-azure.k8s.it.com", ip: "{{ svc_ip.results[1].stdout }}" }
      - { name: "grafana-azure.k8s.it.com", ip: "{{ svc_ip.results[2].stdout }}" }
      - { name: "app-azure.k8s.it.com", ip: "{{ svc_ip.results[3].stdout }}" }
