apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
